apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dotwebstack
  name: dotwebstack
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dotwebstack
    spec:
      containers:
      - image: linkeddataacr.azurecr.io/bp4mc2-dws:v20190730.1
        name: dotwebstack
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
