apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: fuseki
  name: fuseki
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fuseki
    spec:
      containers:
      - image: linkeddataacr.azurecr.io/bp4mc2-fuseki:v20190730.1
        name: fuseki
        ports:
        - containerPort: 3030
        resources: {}
      restartPolicy: Always
status: {}
