apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ldt-config
  name: ldt-config
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ldt-config
    spec:
      containers:
      - args:
        - /bin/sleep
        - infinity
        image: linkeddataacr.azurecr.io/bp4mc2-ldt-config:v20190730.1
        name: ldt-config
        resources: {}
      imagePullSecrets:
      - name: ldt-secret
      restartPolicy: Always
status: {}
