apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: virtuoso
  name: virtuoso
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: virtuoso
    spec:
      containers:
      - image: linkeddataacr.azurecr.io/bp4mc2-virtuoso:v20190730.1
        name: virtuoso
        ports:
        - containerPort: 8890
        resources: {}
      imagePullSecrets:
      - name: ldt-secret
      restartPolicy: Always
status: {}
