version: '3.3'

services:

  webserver:
    image: bp4mc2-nginx
    ports:
      - "8888:80"

  fuseki:
    image: bp4mc2-fuseki
    ports:
      - "3030:3030"

  virtuoso:
    image: bp4mc2-virtuoso
    ports:
      - "8890:8890"

  dotwebstack:
    image: bp4mc2-dws
    ports:
      - "8081:8080"

  ldt:
    image: bp4mc2-ldt
    ports:
      - "8080:8080"
