version: '3.3'

services:

  webserver:
    image: bp4mc2-nginx
    environment:
      - FUSEKI_HOST=fuseki:3030
      - VIRTUOSO_HOST=virtuoso:8890
      - LDT_HOST=host.docker.internal:8080
      - DOTWEBSTACK_HOST=host.docker.internal:8081
    ports:
      - "80:80"
    command: /bin/bash -c "cp /etc/nginx/conf.d/default.network /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  fuseki:
    image: bp4mc2-fuseki
    ports:
      - "3030:3030"

  virtuoso:
    image: bp4mc2-virtuoso
    ports:
      - "8890:8890"

  dotwebstack:
    image: bp4mc2-dws
    ports:
      - "8081:8080"

  ldt:
    image: bp4mc2-ldt
    environment:
      - CATALINA_HOME=/usr/local/tomcat
    ports:
      - "8080:8080"
    command: /bin/bash -c "/run.sh"
