GRANT SPARQL_UPDATE TO "SPARQL";
GRANT EXECUTE ON DB.DBA.RDF_SPONGE_UP TO "SPARQL", "SPARQL_UPDATE";
GRANT EXECUTE ON DB.DBA.TTLP_EV_NEW_GRAPH TO "SPARQL", "SPARQL_UPDATE";
GRANT EXECUTE ON DB.DBA.L_O_LOOK TO "SPARQL", "SPARQL_UPDATE";
GRANT EXECUTE ON DB.DBA.RL_I2ID TO "SPARQL", "SPARQL_UPDATE";
GRANT EXECUTE ON DB.DBA.RL_I2ID_NP TO "SPARQL", "SPARQL_UPDATE";
